### ISSUE TITLE
Please keep on considering ARM support

### ISSUE THREAD

**Issue by hxhieu** [maxdeviant/peacock#5]
Hi!

Sorry but this is not an issue but more like a contribution comment.

A bit of a background, so I have been researching some Rust game engine that can work on the ARM devices such as the Raspberry Pi or my Gameshell.

Thanks to this [list](https://arewegameyet.com/categories/engines/)  so I have found Peacock and so far this is the only engine that could be able to run on the Gameshell!!! (then of course can run on the RPi since the RPi has a much better graphics driver)

Thanks for the good work and your engine goals seem fair but please also consider the ARM devices too. They are becoming tier 1 support from Rust soon.

Cheers,
H

**Comment by maxdeviant** [comment]
@hxhieu Thank you for your feedback!

It's good to hear that Peacock runs on ARM. Truth be told I didn't do anything specifically to enable this, so it seems like a bit of a happy accident 😄 

I don't currently have any intention of doing anything that would drop ARM support, but I will try to keep ARM in mind as the engine continues to evolve.

On a more general note, I would be more than happy to hear from you more about your experience with using Peacock. As you work with it, please let me know if there are specific areas that are lacking and we can work together to see if we can fill those gaps.
